import type { NextPage } from 'next'
import Head from 'next/head'
import { getSession, useSession } from 'next-auth/react'

import Layout from '../components/Layout'
import Counter from '../features/counter/Counter'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data: session } = useSession()
  console.log(session)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Counter />
      </Layout>
    </div>
  )
}

export default Home
