import type { NextPage } from 'next'
import Head from 'next/head'

import Counter from '@/features/counter/Counter'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Counter />
		</div>
	)
}

export default Home
