name: format and lint
on: [push]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: yarn run lint
      - name: Format
        run: yarn run format
      - name: Unit test
        run: yarn run test
